spring.application.name=storage

spring.datasource.url=jdbc:mysql://localhost:3306/cloud_storage_db
spring.datasource.username=root
spring.datasource.password=Vina@1618

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB